/**
 * SINGLE SOURCE OF TRUTH.
 * Every page renders from this file and the assistant answers from this file.
 * That makes it structurally impossible for the assistant to contradict the site.
 *
 * `body` is plain text: "## Heading" lines, blank-line paragraphs, "- " bullets,
 * "> " quotes, **bold** and `code` inline. components/Prose.tsx renders it;
 * lib/prompt.ts feeds it to the model verbatim.
 */

import "server-only";
import { SITE } from "./site";

export { SITE };

export type Group = "live" | "building" | "enterprise" | "earlier";

export type Entry = {
  id: string; // "work.fuso" — doubles as the citation tag
  section: string; // "Work"
  label: string; // "Mitsubishi Fuso" — what the source tag displays
  href?: string; // "/work/mitsubishi-fuso" — where the tag links
  group?: Group;
  owner?: "Cubastion Consulting" | "Personal"; // who the work was done for
  status?: string; // "LIVE", "IN BUILD", "ENTERPRISE DELIVERY", "EARLIER"
  kind?: "AI" | "PRODUCT";
  period?: string;
  role?: string;
  summary?: string; // the one-liner used on the landing index
  body: string; // full prose — rendered on the page AND fed to the model
  stack?: string[];
  links?: { label: string; href: string }[];
  tags: string[]; // reserved for selection; the whole corpus is sent today, nothing reads these
};


export const corpus: Entry[] = [
  // ---------------------------------------------------------------- hero
  {
    id: "hero",
    section: "Home",
    label: "Overview",
    href: "/",
    body: `I am Shashank Jindal, an AI and enterprise-systems consultant based in New Delhi, India.

${SITE.h1}

${SITE.subline}

I am open to consulting work and full-time AI roles. The fastest way to reach me is email: ${SITE.email}. My resume is at ${SITE.resumePath}.`,
    tags: ["who", "overview", "summary", "what does he do", "intro", "delhi", "siebel", "ai", "consultant", "available", "looking for", "open to"],
  },

  // -------------------------------------------------------------- offers
  {
    id: "offer.assistants",
    section: "What I do",
    label: "Grounded AI assistants",
    href: "/#what-i-do",
    summary: "Grounded AI assistants over your own documents",
    body: `## 01 · Grounded AI assistants over your own documents

An assistant that answers from your policies, manuals or records — and cites which document each answer came from. When the answer isn't in the corpus it says so and stops. No invention, no confident guessing, no support ticket generated by a wrong answer.`,
    tags: ["grounded", "rag", "retrieval", "documents", "citations", "cite", "policies", "manuals", "assistant", "chatbot", "hallucination", "offer", "service"],
  },
  {
    id: "offer.agents",
    section: "What I do",
    label: "Voice and chat agents",
    href: "/#what-i-do",
    summary: "Voice and chat agents, end to end",
    body: `## 02 · Voice and chat agents, end to end

Conversation design, a deterministic state machine in code, a narrow LLM classification layer, telephony and SMS. Barge-in and sub-second first audio treated as requirements, not polish — both are painful to retrofit.`,
    tags: ["voice", "chat", "agent", "telephony", "sms", "state machine", "barge-in", "latency", "ivr", "phone", "offer", "service"],
  },
  {
    id: "offer.enterprise",
    section: "What I do",
    label: "AI into enterprise systems",
    href: "/#what-i-do",
    summary: "AI into enterprise systems",
    body: `## 03 · AI into enterprise systems

Siebel, Oracle, and the batch jobs and integrations around them. Getting an agent to read real records and write back without breaking the workflows the business already runs on — which is where most pilots quietly stop.

Usually the first job is deciding whether any of it is worth building. I have scoped 35+ initiatives and written 20+ PRDs that shipped; I have also killed features at discovery and saved the build.`,
    tags: ["enterprise", "siebel", "oracle", "integration", "batch", "crm", "pilot", "scoping", "discovery", "prd", "worth building", "offer", "service"],
  },

  // ---------------------------------------------------------------- work
  {
    id: "work.hrbot",
    section: "Work",
    label: "HR Policy Assistant",
    href: "/work/hr-policy-assistant",
    group: "live",
    owner: "Personal",
    status: "LIVE",
    kind: "AI",
    role: "Personal project",
    summary: "Grounded RAG over HR policy documents, cited answers, Microsoft Entra SSO",
    body: `A grounded assistant over a consulting firm's HR policy documents — cited answers, designed refusals, enterprise SSO.

## Context

A consulting firm's HR policy lives in a pile of documents nobody reads end to end. So people ask a colleague, ask HR, or guess — and guessing about comp-off eligibility or leave accrual produces a support load and the occasional wrong decision.

## What I did

A retrieval assistant over the official policy documents. Every answer cites the document it came from, at the bottom of the response, so the reader can go and check.

When a question isn't covered by the corpus, it declines and says nothing further. That refusal was designed in from the start, not added as a fallback after it embarrassed someone. The interesting part of a grounded system isn't what it answers — it's what it refuses.

Access is restricted to company accounts through Microsoft Entra SSO, so the policy corpus never leaves the people it applies to.

## Outcome

Running internally on live policy documents at cubastion-hr-bot.onrender.com. Sign-in is restricted to company accounts through Microsoft Entra SSO, so the app is reachable but the corpus stays inside the firm.`,
    stack: ["Retrieval over policy documents", "Source citation", "Microsoft Entra SSO", "Render"],
    links: [{ label: "cubastion-hr-bot.onrender.com", href: "https://cubastion-hr-bot.onrender.com" }],
    tags: ["hr", "policy", "rag", "retrieval", "grounded", "citation", "refusal", "sso", "entra", "microsoft", "assistant", "leave", "comp-off", "documents", "live"],
  },
  {
    id: "work.dhobidash",
    section: "Work",
    label: "Dhobi Dash",
    href: "/work/dhobi-dash",
    group: "live",
    owner: "Personal",
    status: "LIVE",
    kind: "PRODUCT",
    period: "Aug 2025 –",
    role: "Founder — discovery, spec, build, go-to-market",
    summary: "7 shops on monthly retainers, 13 months",
    body: `A dry-cleaning shop management product. Seven shops paying monthly retainers, thirteen months on.

## How it started

A shop owner two streets away handed me six paper registers and asked me to find an order from the previous month.

That's how small dry-cleaning businesses in India run — customer details, order history and payments in handwritten books. When a customer turns up without their receipt, the owner searches by hand while a queue builds behind them. Partial payments get tracked from memory.

## Why nothing existing solves it

The competitor here isn't other software, it's the register. Retail POS systems lose to a paper book because they're built around product inventory, not garment service workflow — and they demand training from users who have no appetite for it. Accounting apps track money but not orders. So the register wins, and the shop stays on paper.

## What I built

A mobile-first order management system specced around one constraint: a shop owner with low digital literacy has to use it during a morning rush without training.

Customer lookup by phone number. Order creation in under 30 seconds for a repeat customer, with price auto-filled from a service and item master. Status tracking through the real lifecycle — received, in progress, ready, delivered. Partial payments with a running balance.

The business rules are where this class of product usually corrupts its own data, so they're enforced rather than advised: an order can't be marked delivered while a balance is outstanding, delivered orders become read-only, a payment can't exceed what's pending, and a duplicate phone number is rejected on entry.

## The build decision

The risk was never the code — it was whether a shop owner would change how he works. So I put the time into discovery and the spec, and used an AI builder to reach a working product in a week.

I sold it to the man with the six registers that same week. Six more shops followed inside three months.

## Outcome

Seven shops on monthly retainers since August 2025. All seven still active.

## Try it

The app is live at dhobi-dash-manager.lovable.app. Sign in with the demo account: email **shashankjindal1306@gmail.com**, password **123456789**. It is a dummy account with sample data, so click around freely, but please don't enter real customer details.`,
    stack: ["Mobile-first web app", "Service & item master", "Enforced business rules", "AI builder for the first cut"],
    // TODO (brief §24): add the PRD PDF link when ready.
    links: [{ label: "dhobi-dash-manager.lovable.app", href: "https://dhobi-dash-manager.lovable.app" }],
    tags: ["dhobi", "dash", "dry cleaning", "laundry", "shop", "retainer", "product", "founder", "customers", "first customer", "ai builder", "business rules", "data clean", "spec", "prd", "live", "paying"],
  },
  {
    id: "work.tddgen",
    section: "Work",
    label: "Siebel TDD Generator",
    href: "/work/tdd-generator",
    group: "live",
    owner: "Personal",
    status: "LIVE",
    kind: "AI",
    role: "Personal project",
    summary: "Turns a change request into a structured technical design document in seconds",
    body: `Turns a Siebel change request into a structured technical design document in seconds.

## Context

Technical Design Documents for medium and large change requests cost a Siebel delivery team hours of repetitive formatting per CR. The thinking takes twenty minutes; the document takes the afternoon.

## What I did

A generator that takes a CR ID, a description and a free-text object list, and returns structured TDD output. Schema-driven, so the result is consistent across people and ready for downstream automation rather than being a wall of prose.

Built it because I was the one writing them.

## Outcome

Live at tdd-generator.fly.dev. It does what it says; no usage or adoption figures are claimed for it.`,
    stack: ["Node.js", "Schema-driven generation", "Fly.io"],
    links: [{ label: "tdd-generator.fly.dev", href: "https://tdd-generator.fly.dev" }],
    tags: ["tdd", "technical design document", "generator", "change request", "cr", "siebel", "schema", "consistent", "node", "fly", "live"],
  },
  {
    id: "work.bookingagent",
    section: "Work",
    label: "AI Service Booking Agent",
    href: "/work/booking-agent",
    group: "building",
    owner: "Personal",
    status: "IN BUILD",
    kind: "AI",
    role: "Personal project",
    summary: "Voice agent for vehicle service centres. The model never drives the flow.",
    body: `A voice agent for vehicle service centres, designed so the model never drives the flow.

## Context

A vehicle service centre runs on its phone line. Calls land during opening hours and compete with the people standing at the counter; after hours they're simply lost. The obvious fix is an IVR, and an IVR can't accept "Thursday if you've got something."

## What I did

Designed it as a deterministic state machine in code, with the LLM confined to one job: turning a spoken sentence into a small JSON object. The model never decides what happens next, never sees customer data, and never writes prose — every line the agent speaks is a code template with database values interpolated.

That constraint is what makes an on-premise deployment possible, and on-premise is often the only reason an enterprise buyer says yes.

The flow identifies a caller by number, pulls the vehicle and next due service, books against per-day and per-service-type capacity with the booking write guarded so it cannot overbook, and confirms by SMS.

Voice work is in the design from the start rather than bolted on: barge-in, a sub-second budget to first audio, and response variation drawn from pools of three to five phrasings selected in code rather than generated.

## Outcome

Backend, schema and capacity model built and verified. Business-rules layer in progress. The metric it will be judged on is booking completion rate — the share of calls ending in a confirmed booking rather than a handoff.`,
    stack: ["Node", "Express", "SQLite, SQL kept Postgres-portable", "Narrow LLM classification layer"],
    tags: ["booking", "voice", "agent", "service centre", "vehicle", "ivr", "state machine", "deterministic", "json", "on-premise", "sms", "capacity", "overbook", "barge-in", "latency", "in build", "when done", "completion rate"],
  },
  {
    id: "work.voltas",
    section: "Work",
    label: "Voltas",
    href: "/work/voltas",
    group: "enterprise",
    owner: "Cubastion Consulting",
    status: "ENTERPRISE DELIVERY",
    period: "Apr 2026 –",
    role: "AMS and change request team, Cubastion Consulting",
    summary: "Production monitoring across 8 component groups; payout cycle 5 hours → verification",
    body: `Production monitoring across eight Siebel component groups, and a payout cycle taken from five hours to a morning verification.

## Context

Voltas runs service operations on a Siebel estate deployed across Kubernetes, with franchisee payouts flowing downstream into SAP. Two problems: nobody could see the health of the estate without logging into it, and the payout cycle was a five-hour manual process running twice a month.

## What I did — voltasmon, production monitoring

A single view covering eight component groups: application interface tier, app servers, cluster and nodes, gateway server, Siebel servers, database, OBIEE, and miscellaneous services.

Per node it reports CPU, memory and disk, component status, JVM heap, and inbound SOAP and REST call counts shown as **successful against total** — so an integration degrading shows up as a ratio moving, not as a ticket three hours later. Environment switching, per-node refresh timestamps, and an admin surface for configuration.

The skeleton came from a monitoring tool I'd built on the Mitsubishi Fuso account; I ported it here and extended it for this estate. Shell scripts underneath.

## What I did — FPO automation

Franchisee payout generation ran manually for about five hours, twice a month on the 1st and the 16th, covering roughly 1,300 franchisees — with a hard downstream dependency, because the output feeds a SAP batch. Automated the cycle end to end. What remains is one report verified each morning before the batch fires.

## Outcome

Estate health visible in one place across eight component groups and every node. Payout generation goes from ~5 hours to a morning verification, twice monthly across ~1,300 franchisees. The automation is in development and due live within three months.

voltasmon is an internal production tool. There is no public link.`,
    stack: ["Oracle Siebel on Kubernetes", "Shell scripting", "SAP batch interface", "OBIEE"],
    tags: ["voltas", "monitoring", "voltasmon", "kubernetes", "component groups", "payout", "fpo", "franchisee", "sap", "obiee", "soap", "rest", "cubastion", "ams", "enterprise", "current"],
  },
  {
    id: "work.hero",
    section: "Work",
    label: "Hero",
    href: "/work/hero",
    group: "enterprise",
    owner: "Cubastion Consulting",
    status: "ENTERPRISE DELIVERY",
    period: "Dec 2025 – Mar 2026",
    role: "Cubastion Consulting",
    summary: "100,000 records a day: ~10,000 EAI runs replaced with one nightly job",
    body: `100,000 lead records a day, moved off the business layer and onto the extension schema.

## Context

Hero's lead data originates in LeadSquared, a third-party platform, and has to reach Siebel. Volume is around **100,000 records a day**.

The supported route is EAI, through the business layer. At that volume it means roughly **ten thousand separate runs** to move one day's data — slow, fragile, and competing with everything else on the instance.

## What I did

Moved it to the extension schema. LeadSquared writes to its own database and hands off to the middleware team, who have access to \`SIEBELEXT\`. A single job at 22:00 transfers the day's records from the extension schema into Siebel's main tables.

Ten thousand EAI invocations become one nightly job.

That's a deliberate trade: you buy throughput and give up the validation and event logic the business layer would have applied, so validation has to happen before the data arrives. Correct at 100,000 rows a day; wrong at low volume.

## Outcome

Zero reported issues since it went to production.

## The part worth telling

Once it was running, the business came back asking for an API — the same data, on demand rather than as a nightly batch. Which is the usual shape of this work: solving the problem as stated changes what they want next.`,
    stack: ["Oracle Siebel", "SIEBELEXT extension schema", "Oracle SQL", "EAI", "Scheduled jobs"],
    tags: ["hero", "leadsquared", "leads", "eai", "extension schema", "siebelext", "nightly job", "batch", "business layer", "throughput", "validation", "trade off", "100000", "cubastion", "enterprise"],
  },
  {
    id: "work.airtel",
    section: "Work",
    label: "Airtel",
    href: "/work/airtel",
    group: "enterprise",
    owner: "Cubastion Consulting",
    status: "ENTERPRISE DELIVERY",
    period: "Dec 2024 – Nov 2025",
    role: "Cubastion Consulting",
    summary: "Real-time discount integration on order capture. +17% client revenue",
    body: `Real-time discount integration on order capture, with the validation layer that keeps bad orders out of billing.

## Context

Order capture at telecom scale, where discounts are applied while the customer is on the line. An order carrying bad discount data doesn't fail loudly — it fails downstream in fulfilment and billing, after the customer has already been told yes.

## What I did

Built the real-time discount integration. Siebel calls the discount service over REST at the point of order capture rather than relying on a synced price list. I designed the request and response transformation, the staging tables the responses land in, and the validation layer that runs before an order can move forward.

That validation layer exists for one reason: order data integrity before anything reaches fulfilment and billing. It's the part nobody notices until it's missing.

Alongside it: 20+ change requests across applets, views and business components, 10+ workflows automating customer onboarding and request handling, and 8+ Open UI customisations using PR/PM and JavaScript.

## Outcome

Contributed to a 17% client revenue uplift. Page load improved ~15%. 60+ defects resolved at >95% SLA adherence.`,
    stack: ["Oracle Siebel", "REST integration", "Open UI (PR/PM)", "Oracle SQL", "eScript"],
    tags: ["airtel", "telecom", "discount", "order capture", "rest", "validation", "billing", "fulfilment", "staging", "17%", "revenue", "open ui", "escript", "workflows", "cubastion", "enterprise"],
  },
  {
    id: "work.fuso",
    section: "Work",
    label: "Mitsubishi Fuso",
    href: "/work/mitsubishi-fuso",
    group: "enterprise",
    owner: "Cubastion Consulting",
    status: "ENTERPRISE DELIVERY",
    period: "Oct 2023 – Nov 2024",
    role: "Cubastion Consulting",
    summary: "200+ dealerships, 2,500+ service centres. Contract turnaround 5 days → 6 hours",
    body: `Sales and service across 200+ dealerships and 2,500+ service centres, and the DocuSign integration that took contract turnaround from five days to six hours.

## Context

Sales and service on Siebel across **200+ dealerships and 2,500+ service centres**, in a high-availability environment where a bad release is felt immediately across the network.

## What I did

Delivered 35+ change requests across sales and service, configuring 25+ applets, views and business components covering dealer and vehicle lifecycle — with no critical production issues.

Built the DocuSign integration using outbound web services, integration objects and workflows, so contracts and service documents are signed digitally rather than printed and couriered. Buy-versus-build went to buy, optimised for speed to revenue, and it shipped in four weeks.

Ran 130+ production incidents to root cause rather than patching symptoms, which took recurring issues down by about 30%.

Also built the monitoring tool that gave the team a single view of the Siebel estate's health — component status, node resources and integration call volumes — rather than requiring someone to log in and check. It was good enough that its skeleton was later ported to another account.

## Outcome

Contract turnaround from **5 days to 6 hours**. 95% user adoption within three months. 10% reduction in cost per document. Two production releases through cutover and hypercare.`,
    stack: ["Oracle Siebel", "Outbound web services", "Integration objects", "Workflows", "DocuSign"],
    tags: ["fuso", "mitsubishi", "dealerships", "service centres", "docusign", "contract", "turnaround", "estate", "monitoring", "incidents", "root cause", "hypercare", "cutover", "cubastion", "enterprise", "first account"],
  },
  {
    id: "work.easyapply",
    section: "Work",
    label: "EasyApply.ai",
    group: "earlier",
    owner: "Personal",
    status: "EARLIER",
    kind: "AI",
    summary: "AI SaaS that autofills job applications. The hard part was field mapping, not generation.",
    body: `EasyApply.ai — an AI SaaS that autofills job applications. The hard part was field mapping, not generation. Built with Next.js, Node, MongoDB and OpenRouter. An earlier project; it has no dedicated page.`,
    stack: ["Next.js", "Node", "MongoDB", "OpenRouter"],
    tags: ["easyapply", "job applications", "autofill", "field mapping", "saas", "earlier", "openrouter", "mongodb"],
  },

  // ---------------------------------------------------------- principles
  {
    id: "principles",
    section: "How I build",
    label: "How I build",
    href: "/how-i-build",
    body: `Six opinions I'll bring to your project on day one. Each came out of a decision that had to be made on a real flow — most of them on the AI Service Booking Agent — and each is arguable; I'm happy to argue them. The six: the model never drives the flow; customer data never reaches the model; ground every answer, and cite it; natural isn't chatty; every dead end is still a call; pick a metric that can prove you wrong.`,
    tags: ["principles", "how i build", "opinions", "where from", "origin", "contentious", "arguable", "broken", "list"],
  },
  {
    id: "principle.i",
    section: "How I build",
    label: "The model never drives the flow",
    href: "/how-i-build#i",
    summary: "The model never drives the flow",
    body: `## i · The model never drives the flow

A deterministic state machine in code decides what happens next. The LLM turns one utterance into a small JSON object and nothing more. Business rules that live in a prompt are business rules you cannot test.`,
    tags: ["principle", "state machine", "deterministic", "flow", "prompt", "business rules", "testable", "json"],
  },
  {
    id: "principle.ii",
    section: "How I build",
    label: "Customer data never reaches the model",
    href: "/how-i-build#ii",
    summary: "Customer data never reaches the model",
    body: `## ii · Customer data never reaches the model

Every line the agent speaks is a code template with database values interpolated in. This is what makes an on-premise deployment possible — and on-premise is often the only reason an enterprise buyer says yes.`,
    tags: ["principle", "customer data", "privacy", "on-premise", "templates", "pii", "security"],
  },
  {
    id: "principle.iii",
    section: "How I build",
    label: "Ground every answer, and cite it",
    href: "/how-i-build#iii",
    summary: "Ground every answer, and cite it",
    body: `## iii · Ground every answer, and cite it

An assistant that answers from your documents should show which document. When the answer isn't there, it says so and stops. The interesting part of a grounded system isn't what it answers — it's what it refuses.`,
    tags: ["principle", "grounded", "cite", "citation", "refusal", "documents", "hallucination"],
  },
  {
    id: "principle.iv",
    section: "How I build",
    label: "Natural isn't chatty",
    href: "/how-i-build#iv",
    summary: "Natural isn't chatty",
    body: `## iv · Natural isn't chatty

Variation comes from pools of three to five phrasings per turn, selected in code, not generated. Fake warmth reads worse than clean efficiency and burns call time. Aim for a competent receptionist who knows the answer, not a friend.`,
    tags: ["principle", "natural", "chatty", "phrasings", "variation", "tone", "receptionist", "warmth"],
  },
  {
    id: "principle.v",
    section: "How I build",
    label: "Every dead end is still a call",
    href: "/how-i-build#v",
    summary: "Every dead end is still a call",
    body: `## v · Every dead end is still a call

"Thursday's completely full for that kind of job, I'm afraid — the workshop can sometimes squeeze people in, I'll text you their direct number." Same outcome as an error message, same lead captured, a completely different call.`,
    tags: ["principle", "dead end", "error", "fallback", "handoff", "lead", "graceful"],
  },
  {
    id: "principle.vi",
    section: "How I build",
    label: "Pick a metric that can prove you wrong",
    href: "/how-i-build#vi",
    summary: "Pick a metric that can prove you wrong",
    body: `## vi · Pick a metric that can prove you wrong

For a booking agent it's the share of calls ending in a confirmed booking. Published benchmarks in this space are vendor marketing — the widely-quoted IVR abandonment figures trace back to no primary source. Measure your own call log for a week instead.`,
    tags: ["principle", "metric", "measure", "benchmark", "completion rate", "ivr abandonment", "evidence", "contentious"],
  },

  // ---------------------------------------------------------- background
  {
    id: "background",
    section: "About",
    label: "Background",
    href: "/about",
    body: `## Three job titles, one useful combination.

I joined Cubastion Consulting in October 2023 as a graduate engineer writing Node and SQL. Within a year I was deep in Oracle Siebel — workflows, integration objects, eScript, Open UI, EAI — across four of the firm's more demanding accounts. Two promotions in three years: graduate trainee, associate consultant, senior associate consultant.

Somewhere in there I picked up the product side of these platforms too — discovery, requirements, PRDs, UAT, release coordination. 35+ initiatives scoped, 20+ PRDs shipped.

And I kept building my own things. One of them, Dhobi Dash, has seven shops paying monthly retainers.

None of those three tracks is remarkable on its own. Together they're the shape an AI project actually needs: someone who can work out what's worth automating, who already knows what the system underneath will allow, and who can then go and build it.

## At a glance

- Current: Senior Associate Consultant, Cubastion Consulting
- Since: October 2023
- Accounts: Mitsubishi Fuso · Airtel · Hero · Voltas
- Education: B.Tech, Electronics & Communication — Maharaja Agrasen Institute of Technology, 2023 · 8.8 CGPA
- Recognition: Diamond Award, 2024
- Certification: AI for Product Management — Pendo
- Languages: English, Hindi
- Based: New Delhi, India`,
    tags: ["background", "career", "cubastion", "graduate", "promotion", "senior associate consultant", "education", "btech", "maharaja agrasen", "cgpa", "diamond award", "pendo", "certification", "languages", "hindi", "english", "experience", "years", "product manager", "why ai", "strongest", "journey"],
  },

  // --------------------------------------------------------------- stack
  {
    id: "stack.ai",
    section: "Stack",
    label: "AI & agents",
    href: "/about#stack",
    body: `AI & agents — Grounded retrieval with source citation · deterministic state machines · LLM classification layers · slot extraction · refusal design · on-premise constraints · OpenRouter`,
    stack: ["Grounded retrieval with source citation", "Deterministic state machines", "LLM classification layers", "Slot extraction", "Refusal design", "On-premise constraints", "OpenRouter"],
    tags: ["stack", "ai", "agents", "llm", "retrieval", "openrouter", "skills", "tools"],
  },
  {
    id: "stack.crm",
    section: "Stack",
    label: "Enterprise CRM",
    href: "/about#stack",
    body: `Enterprise CRM — Oracle Siebel · Workflow & subprocesses · EAI, integration objects, data maps · eScript · Open UI (PR/PM) · Order Management, pricing & discounting · extension schemas · EIM`,
    stack: ["Oracle Siebel", "Workflow & subprocesses", "EAI, integration objects, data maps", "eScript", "Open UI (PR/PM)", "Order Management, pricing & discounting", "Extension schemas", "EIM"],
    tags: ["stack", "siebel", "crm", "eai", "escript", "open ui", "eim", "workflow", "order management", "skills"],
  },
  {
    id: "stack.backend",
    section: "Stack",
    label: "Backend",
    href: "/about#stack",
    body: `Backend — Node.js · Express · REST & SOAP · WebSockets · WebRTC · API design · auth & RBAC · Docker`,
    stack: ["Node.js", "Express", "REST & SOAP", "WebSockets", "WebRTC", "API design", "Auth & RBAC", "Docker"],
    tags: ["stack", "backend", "node", "express", "rest", "soap", "websockets", "webrtc", "docker", "skills"],
  },
  {
    id: "stack.data",
    section: "Stack",
    label: "Data",
    href: "/about#stack",
    body: `Data — Oracle SQL & PL/SQL · MySQL · MongoDB · SQLite · schema design · indexing & query performance · Elasticsearch · Redis`,
    stack: ["Oracle SQL & PL/SQL", "MySQL", "MongoDB", "SQLite", "Schema design", "Indexing & query performance", "Elasticsearch", "Redis"],
    tags: ["stack", "data", "sql", "plsql", "mysql", "mongodb", "sqlite", "elasticsearch", "redis", "database", "skills"],
  },
  {
    id: "stack.frontend",
    section: "Stack",
    label: "Frontend",
    href: "/about#stack",
    body: `Frontend — React · Next.js · Redux · TypeScript · Tailwind`,
    stack: ["React", "Next.js", "Redux", "TypeScript", "Tailwind"],
    tags: ["stack", "frontend", "react", "next", "redux", "typescript", "tailwind", "skills"],
  },
  {
    id: "stack.product",
    section: "Stack",
    label: "Product",
    href: "/about#stack",
    body: `Product — Discovery & user research · PRDs and user stories · roadmapping · stakeholder management · UAT and launch · Jira, Confluence, Figma`,
    stack: ["Discovery & user research", "PRDs and user stories", "Roadmapping", "Stakeholder management", "UAT and launch", "Jira, Confluence, Figma"],
    tags: ["stack", "product", "discovery", "prd", "roadmap", "stakeholder", "uat", "jira", "confluence", "figma", "skills"],
  },

  // ----------------------------------------------------- this assistant
  {
    id: "assistant",
    section: "This site",
    label: "This assistant",
    href: "/how-i-build#iii",
    body: `The assistant on this site is a grounded retrieval assistant Shashank built. It answers on his behalf, in the first person, only from a fixed set of about thirty entries he wrote — the same file the pages render from — and names the entries it used, which the interface shows as source chips linking to the page each entry lives on. It is software, not Shashank typing live. There is no vector database and no embeddings: the corpus is small enough to send whole. Questions about salary, notice period, availability or personal life are refused by a deny-list before any model call. Common questions are answered from a pre-generated file with no model call; only novel typed questions reach the model. When the entries don't cover something it says so and gives the email rather than guessing.`,
    tags: ["assistant", "what are you", "are you real", "are you human", "how does this work", "this site", "rail", "chatbot", "vector database", "embeddings", "rag", "grounded", "refuse", "model"],
  },

  // ------------------------------------------------------------- contact
  {
    id: "contact",
    section: "Contact",
    label: "Contact",
    href: "/#contact",
    body: `If you're weighing up an AI project, I'll tell you honestly whether it's worth building. That conversation is free and usually short. If it is worth building, we can talk about how. If it isn't, you've saved a quarter.

- Email: ${SITE.email}
- Phone: ${SITE.phone}
- LinkedIn: ${SITE.linkedinHandle}
- GitHub: ${SITE.githubHandle}
- Resume (PDF): ${SITE.resumePath}

${SITE.location} · ${SITE.availability}.`,
    links: [{ label: "Resume (PDF)", href: SITE.resumePath }],
    tags: ["contact", "resume", "cv", "email", "phone", "linkedin", "github", "reach", "hire", "consulting", "full-time", "roles", "open to", "available", "location", "delhi", "remote"],
  },
];

// ------------------------------------------------------------------ helpers

export const byId = (id: string): Entry | undefined => corpus.find((e) => e.id === id);

export const entryIds = corpus.map((e) => e.id);

/** Work entries in landing order (includes EasyApply, which has no page). */
export const workEntries = corpus.filter((e) => e.id.startsWith("work."));

/** Work entries that have a dedicated page, in walk order for prev/next. */
export const caseStudies = workEntries.filter((e) => Boolean(e.href));

export const slugOf = (e: Entry) => (e.href ?? "").replace(/^\/work\//, "");

export const bySlug = (slug: string) => caseStudies.find((e) => slugOf(e) === slug);

export const neighbours = (slug: string) => {
  const i = caseStudies.findIndex((e) => slugOf(e) === slug);
  return {
    prev: i > 0 ? caseStudies[i - 1] : undefined,
    next: i >= 0 && i < caseStudies.length - 1 ? caseStudies[i + 1] : undefined,
  };
};

export const offers = corpus.filter((e) => e.id.startsWith("offer."));
export const principles = corpus.filter((e) => e.id.startsWith("principle."));
export const stackGroups = corpus.filter((e) => e.id.startsWith("stack."));

export const groupLabel: Record<Group, string> = {
  live: "Live",
  building: "In build",
  enterprise: "Delivered at Cubastion Consulting",
  earlier: "Earlier",
};

export const groupOrder: Group[] = ["live", "building", "enterprise", "earlier"];

/** One vocabulary for status, kind and owner, shared by the index rows and the case-study header. */
export const statusWord: Record<Group, string> = { live: "Live", building: "In build", enterprise: "Delivered", earlier: "Earlier" };
export const kindWord = (k: Entry["kind"]) => (k === "AI" ? "AI" : k === "PRODUCT" ? "Product" : undefined);
export const ownerWord = (o: Entry["owner"], long = false) =>
  o === "Personal" ? (long ? "Personal project" : "Personal") : o ? (long ? "Cubastion Consulting · client engagement" : "Cubastion Consulting") : undefined;

/** Roman numeral of a principle, taken from its id so reordering never breaks deep links. */
export const principleNumeral = (e: Entry) => e.id.split(".")[1] ?? "";

export type Source = { id: string; label: string; href?: string };

/** Ids → display sources, deduplicated and dropping unknown ids. */
export const resolveSources = (ids: string[]): Source[] =>
  Array.from(new Set(ids))
    .map((id) => byId(id))
    .filter((e): e is Entry => Boolean(e))
    .map((e) => ({ id: e.id, label: e.label, href: e.href }));

/** Every route a page exists for. The API accepts a route hint only from this set. */
export const validRoutes: ReadonlySet<string> = new Set(["/", "/how-i-build", "/about", ...caseStudies.map((e) => e.href!)]);
